import path from "node:path";
import type { PrismaClient } from "@prisma/client";
// Generated by `prisma generate --schema=prisma/.demo.prisma` (postinstall
// + vercel-build.sh). Static import so the bundler traces the SQLite query
// engine into the serverless output.
import { PrismaClient as DemoPrismaClient } from "../../node_modules/.cache/demo-client";

/**
 * src/lib/demo-db.ts — the LOCAL demo database.
 *
 * Demo accounts are served exclusively from the bundled local SQLite
 * demo db (prisma/db/custom.db) — never from the remote database.
 * This module lazily instantiates a SEPARATE Prisma client for that
 * file (SQLite provider — the main client in production is Postgres
 * and cannot open SQLite files).
 *
 * db.ts routes every Prisma call through this client while a demo
 * session is active (AsyncLocalStorage).
 */

let demoDb: PrismaClient | null = null;
let demoInitError: string | null = null;

/** Absolute file: URL of the bundled demo db (or DEMO_DATABASE_URL). */
export function demoDatabaseUrl(): string {
  const override = process.env.DEMO_DATABASE_URL;
  if (override) return override;
  return "file:" + path.join(process.cwd(), "prisma", "db", "custom.db").replaceAll("\\", "/");
}

/** The demo-db client, or null when it is unavailable (generate failed). */
export function getDemoDb(): PrismaClient | null {
  if (demoDb) return demoDb;
  if (demoInitError) return null;
  try {
    demoDb = new DemoPrismaClient({ datasourceUrl: demoDatabaseUrl() }) as unknown as PrismaClient;
  } catch (err) {
    demoInitError = err instanceof Error ? err.message : String(err);
    console.warn("[demo-db] demo SQLite client unavailable:", demoInitError);
  }
  return demoDb;
}
