"use client";

/**
 * AI Assistant — Action Dialog (Section 4)
 *
 * ONE reusable dialog component, used for every flag type app-wide.
 * Do not build separate dialogs per flag source.
 *
 * Content (all generated by the AI Assistant):
 * - Headline: plain-language label (Section 0.5) + color
 * - "Why": the specific data/threshold that triggered this, in plain language
 * - "Suggested action": AI-drafted message or action, editable
 * - "Your note" (REQUIRED): 2-3 AI-drafted one-tap options + free-text field
 * - [Cancel] always available, no penalty
 *
 * Rules:
 * - Confirm button is DISABLED until a note (preset selection OR free-text) is provided
 * - Cancel never requires a note
 * - AI drafts, humans decide — nothing auto-sent
 */

import { useState, useEffect } from "react";
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import {
  AlertCircle, AlertTriangle, CheckCircle2, Send, X,
  ChevronDown, ChevronRight, Lightbulb, Brain,
} from "lucide-react";
import { cn } from "@/lib/utils";

export interface ActionDialogData {
  /** Plain-language headline (Section 0.5 — words first, color second) */
  headline: string;
  /** The tier for color: green / amber / red */
  tier: "green" | "amber" | "red";
  /** "Why" — the specific data/threshold that triggered this */
  why: string;
  /** AI-drafted suggested action (editable) */
  suggestedAction: string;
  /** 2-3 AI-drafted one-tap note options, contextual to THIS flag */
  notePresets: string[];
  /** In-action teaching guidance (Section 7) — collapsed by default */
  guidance?: {
    whatItMeans: string;
    principles: string[];
  };
}

interface ActionDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  data: ActionDialogData;
  onConfirm: (note: string, editedAction: string) => void;
  busy?: boolean;
}

export function ActionDialog({
  open,
  onOpenChange,
  data,
  onConfirm,
  busy = false,
}: ActionDialogProps) {
  const [note, setNote] = useState("");
  const [selectedPreset, setSelectedPreset] = useState<string | null>(null);
  const [editedAction, setEditedAction] = useState(data.suggestedAction);
  const [showGuidance, setShowGuidance] = useState(false);

  // Reset state when dialog opens
  useEffect(() => {
    if (open) {
      setNote("");
      setSelectedPreset(null);
      setEditedAction(data.suggestedAction);
      setShowGuidance(false);
    }
  }, [open, data.suggestedAction]);

  // The "effective note" — either the free-text note or the selected preset
  const effectiveNote = selectedPreset || note.trim();
  const canConfirm = effectiveNote.length > 0 && !busy;

  const handlePresetClick = (preset: string) => {
    if (selectedPreset === preset) {
      setSelectedPreset(null); // toggle off
    } else {
      setSelectedPreset(preset);
      setNote(""); // clear free-text when selecting a preset
    }
  };

  const handleConfirm = () => {
    if (!canConfirm) return;
    onConfirm(effectiveNote, editedAction);
  };

  const tierConfig = {
    green: { color: "text-emerald-600", bg: "bg-emerald-50 dark:bg-emerald-950/20", border: "border-emerald-300 dark:border-emerald-800", icon: CheckCircle2 },
    amber: { color: "text-amber-600", bg: "bg-amber-50 dark:bg-amber-950/20", border: "border-amber-300 dark:border-amber-800", icon: AlertTriangle },
    red: { color: "text-rose-600", bg: "bg-rose-50 dark:bg-rose-950/20", border: "border-rose-300 dark:border-rose-800", icon: AlertCircle },
  };

  const config = tierConfig[data.tier];
  const Icon = config.icon;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-lg">
        <DialogHeader>
          <div className="flex items-center gap-2">
            <div className={cn("w-8 h-8 rounded-lg flex items-center justify-center", config.bg, config.border, "border")}>
              <Icon className={cn("w-4 h-4", config.color)} />
            </div>
            <DialogTitle className="text-base">{data.headline}</DialogTitle>
          </div>
        </DialogHeader>

        <div className="space-y-4">
          {/* Why */}
          <div className={cn("p-3 rounded-lg border", config.bg, config.border)}>
            <div className="text-xs font-semibold text-muted-foreground mb-1">Why this was flagged</div>
            <p className="text-sm text-foreground">{data.why}</p>
          </div>

          {/* Suggested action (editable) */}
          <div>
            <Label className="text-xs font-semibold text-muted-foreground">Suggested action (editable)</Label>
            <Textarea
              value={editedAction}
              onChange={(e) => setEditedAction(e.target.value)}
              className="mt-1 text-sm"
              rows={3}
              placeholder="AI-drafted action — edit as needed"
            />
          </div>

          {/* Your note (REQUIRED) */}
          <div>
            <Label className="text-xs font-semibold text-muted-foreground">
              Your note <span className="text-rose-500">*</span> (required)
            </Label>

            {/* One-tap presets */}
            {data.notePresets.length > 0 && (
              <div className="flex flex-wrap gap-1.5 mt-2">
                {data.notePresets.map((preset, i) => (
                  <button
                    key={i}
                    onClick={() => handlePresetClick(preset)}
                    className={cn(
                      "px-2.5 py-1 rounded-full text-[11px] border transition-colors",
                      selectedPreset === preset
                        ? "bg-primary text-primary-foreground border-primary"
                        : "bg-card text-muted-foreground border-border hover:bg-accent"
                    )}
                  >
                    {preset}
                  </button>
                ))}
              </div>
            )}

            {/* Free-text */}
            <Textarea
              value={note}
              onChange={(e) => {
                setNote(e.target.value);
                setSelectedPreset(null); // clear preset when typing
              }}
              className="mt-2 text-sm"
              rows={2}
              placeholder="Or type your own note..."
            />
            {!canConfirm && (
              <p className="text-[10px] text-muted-foreground mt-1">
                Select a suggestion above or type a note to continue.
              </p>
            )}
          </div>

          {/* In-action teaching guidance (Section 7 — collapsed by default) */}
          {data.guidance && (
            <div className="border rounded-lg">
              <button
                onClick={() => setShowGuidance(!showGuidance)}
                className="w-full flex items-center gap-2 p-2.5 text-left hover:bg-accent/50 transition-colors"
              >
                {showGuidance ? <ChevronDown className="w-3.5 h-3.5 text-muted-foreground" /> : <ChevronRight className="w-3.5 h-3.5 text-muted-foreground" />}
                <Lightbulb className="w-3.5 h-3.5 text-amber-500" />
                <span className="text-xs font-medium text-muted-foreground">Guidance for this situation</span>
              </button>
              {showGuidance && (
                <div className="px-3 pb-3 space-y-2">
                  <div>
                    <div className="text-[10px] uppercase tracking-wider text-muted-foreground font-semibold mb-0.5">What this likely means</div>
                    <p className="text-xs text-foreground/80">{data.guidance.whatItMeans}</p>
                  </div>
                  <div>
                    <div className="text-[10px] uppercase tracking-wider text-muted-foreground font-semibold mb-0.5">Principles for approaching it</div>
                    <ul className="space-y-1">
                      {data.guidance.principles.map((p, i) => (
                        <li key={i} className="text-xs text-foreground/80 flex items-start gap-1.5">
                          <Brain className="w-3 h-3 text-primary flex-shrink-0 mt-0.5" />
                          <span>{p}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
              )}
            </div>
          )}
        </div>

        <DialogFooter>
          <Button
            variant="ghost"
            onClick={() => onOpenChange(false)}
            disabled={busy}
          >
            <X className="w-3.5 h-3.5 mr-1" /> Cancel
          </Button>
          <Button
            onClick={handleConfirm}
            disabled={!canConfirm}
            className={cn(data.tier === "red" && "bg-rose-600 hover:bg-rose-700 text-white")}
          >
            {busy ? (
              <>Processing...</>
            ) : (
              <>
                <Send className="w-3.5 h-3.5 mr-1" /> Confirm
              </>
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
