/**
 * Comprehensive Student Report Module
 *
 * Generates a private, in-depth report for a student that combines:
 *   1. Educational analysis — test scores, skill mastery, project progress
 *   2. Psychological analysis — 7-dimension evidence, wellbeing trajectory
 *   3. Behavioral analysis — engagement, attendance, AI-detection signals
 *   4. Mentor analysis — GROW coaching history, mentorship touchpoints
 *   5. Accomplishments — what the student achieved
 *   6. Areas to improve — specific, actionable corrections
 *   7. Management attitude — what the student should focus on to be a
 *      manager / leader (productivity + professionalism signals)
 *
 * The report is generated by the AI from the student's full data trail.
 * It's cached (per-student, invalidated when new evidence arrives) and
 * can be re-generated on demand.
 *
 * Access control:
 *   - Students can view their OWN report
 *   - Teachers can view reports for students in their batch
 *   - Counsellors can view reports for students in their caseload
 *   - Principal + Administrator can view ANY student's report
 *
 * The report is PRIVATE — it's not shared with guardians (it contains
 * internal psychological evidence + mentorship notes).
 */

import { db } from "@/lib/db";
import { callAI } from "@/lib/ai-provider";
import { logger } from "@/lib/logger";
import crypto from "crypto";

export interface ComprehensiveReport {
  id: string;
  userId: string;
  generatedAt: string;
  // Section 1: Educational
  educational: {
    overallScore: number;
    grade: string;
    weeklyTestScores: Array<{ week: number; score: number }>;
    skillMastery: Array<{ topic: string; level: string; trend: string }>;
    projectProgress: number;
    completedTasks: number;
    totalTasks: number;
    projectAnalysis?: {
      score: number;
      execution: number;
      technicalCompetence: number;
      quality: number;
      careerReadiness: number;
      summary: string;
      strengths: string[];
      weaknesses: string[];
      recommendations: string[];
    };
  };
  // Section 2: Psychological (7 dimensions)
  psychological: {
    wellbeingTier: string;
    wellbeingReasons: string[];
    dimensions: Array<{
      dimension: string;
      latestValue: string;
      trend: string;
      evidence: string;
    }>;
    calibrationGap: number | null;
    cognitiveLoad: string;
    mindset: string;
  };
  // Section 3: Behavioral
  behavioral: {
    engagementScore: number;
    moodScore: number;
    attendancePattern: string;
    daysAheadOfSchedule: number;
    plagiarismFlags: number;
    voiceConsistency: string;
    disengagementSignals: string[];
  };
  // Section 4: Mentor
  mentor: {
    touchpointCount: number;
    outcomes: { ongoing: number; resolved: number; escalated: number; noActionNeeded: number };
    growHistory: Array<{ date: string; type: string; outcome: string; note: string }>;
    lastSessionDate: string | null;
  };
  // Section 5: Accomplishments
  accomplishments: string[];
  // Section 6: Areas to improve
  areasToImprove: Array<{
    area: string;
    current: string;
    recommendation: string;
    priority: "high" | "medium" | "low";
  }>;
  // Section 7: Management attitude
  managementAttitude: {
    productivitySignals: string[];
    professionalismSignals: string[];
    leadershipPotential: string;
    managerReadiness: string;
    focusAreas: string[];
  };
  // AI-generated narrative summary
  narrative: string;
  // Cache metadata
  cached: boolean;
  cacheKey: string;
  // ME-5 fix: 'reviewed' flag — AI-generated judgments (managerReadiness,
  // leadershipPotential, etc.) should be reviewed by a human before being
  // used in formal decisions. When false, the UI should show a warning that
  // the report is AI-generated and not yet reviewed.
  reviewed: boolean;
}

/** Gather all the data needed for the comprehensive report. */
async function gatherStudentData(userId: string) {
  const [
    user, psychEvidence, confidenceRatings, skillMastery, touchpoints,
    interactions, weeklyTests, projectTasks, projectReports, wellbeing,
    crisisFlags, alerts, healthSummary, certificates,
  ] = await Promise.all([
    db.user.findUnique({
      where: { id: userId },
      select: {
        id: true, name: true, email: true, role: true, currentWeek: true,
        currentDay: true, selfPacedEnabled: true, createdAt: true, lastLogin: true,
        projectName: true, projectDescription: true, projectType: true,
      },
    }),
    db.psychEvidence.findMany({
      where: { userId },
      orderBy: { createdAt: "desc" },
      take: 100,
      select: { dimension: true, value: true, evidenceText: true, week: true, createdAt: true },
    }),
    db.confidenceRating.findMany({
      where: { userId, actualScore: { not: null } },
      orderBy: { createdAt: "desc" },
      take: 50,
      select: { rating: true, actualScore: true, week: true, createdAt: true },
    }),
    db.skillMastery.findMany({
      where: { userId },
      select: { topic: true, masteryLevel: true, trend: true, evidenceCount: true },
    }),
    db.mentorshipTouchpoint.findMany({
      where: { userId },
      orderBy: { createdAt: "desc" },
      take: 30,
      select: { id: true, type: true, note: true, outcome: true, createdAt: true, actorUserId: true },
    }),
    db.interaction.findMany({
      where: { userId },
      orderBy: { date: "desc" },
      take: 50,
      select: { correctness: true, topic: true, week: true, date: true, pillar: true },
    }),
    db.weeklyTest.findMany({
      where: { userId, status: "completed" },
      orderBy: { week: "asc" },
      select: { week: true, score: true, plagiarismScore: true, completedAt: true, psychAnalysis: true, examinerComment: true },
    }),
    db.projectTask.findMany({
      where: { userId },
      select: { id: true, status: true, week: true, day: true, completedAt: true, isMilestone: true, description: true },
    }),
    db.projectReport.findMany({
      where: { userId },
      orderBy: { week: "desc" },
      take: 10,
      select: { week: true, reportType: true, aiAnalysis: true, submittedAt: true },
    }),
    db.wellbeingState.findUnique({
      where: { userId },
      select: { tier: true, reasonsJson: true },
    }),
    db.crisisFlag.count({ where: { userId } }),
    db.studentAlert.count({ where: { userId } }),
    db.studentHealthSummary.findUnique({
      where: { userId },
      select: { moodScore: true, engagementScore: true, frustrationCount: true, engagementStreak: true },
    }),
    db.certificate.findMany({
      where: { userId },
      select: { id: true, courseName: true, grade: true, score: true, issuedAt: true, verifyToken: true },
    }),
  ]);

  return {
    user, psychEvidence, confidenceRatings, skillMastery, touchpoints,
    interactions, weeklyTests, projectTasks, projectReports, wellbeing,
    crisisFlags, alerts, healthSummary, certificates,
  };
}

/** Score to grade letter. */
function scoreToGrade(score: number): string {
  if (score >= 90) return "A";
  if (score >= 80) return "B";
  if (score >= 70) return "C";
  if (score >= 60) return "D";
  return "F";
}

/** Generate the comprehensive report using AI. */
export async function generateComprehensiveReport(
  userId: string,
  options: { useCache?: boolean; forceRegenerate?: boolean } = {}
): Promise<ComprehensiveReport | null> {
  const data = await gatherStudentData(userId);
  if (!data.user) return null;

  // Cache key: invalidated when new evidence arrives
  const latestEvidence = data.psychEvidence[0]?.createdAt?.toISOString() || data.user.createdAt.toISOString();
  const cacheKey = crypto.createHash("sha256")
    .update(`comprehensive-report:${userId}:${latestEvidence}`)
    .digest("hex");

  // Check cache (unless force-regenerate)
  if (!options.forceRegenerate && options.useCache !== false) {
    const cached = await db.aICache.findUnique({ where: { cacheKey } }).catch(() => null);
    if (cached) {
      try {
        const parsed = JSON.parse(cached.response);
        return { ...parsed, cached: true, cacheKey, reviewed: parsed.reviewed ?? false };
      } catch { /* fall through to regenerate */ }
    }
  }

  // Build the data summary for the AI
  const avgTestScore = data.weeklyTests.length > 0
    ? Math.round(data.weeklyTests.reduce((a, t) => a + (t.score ?? 0), 0) / data.weeklyTests.length)
    : 0;

  const calibrationGap = data.confidenceRatings.length > 0
    ? Math.round(
        data.confidenceRatings.reduce((a, r) => a + (r.rating * 20 - (r.actualScore ?? 0)), 0) /
        data.confidenceRatings.length
      )
    : null;

  const completedTasks = data.projectTasks.filter(t => t.status === "completed").length;
  const totalTasks = data.projectTasks.length;
  const projectProgress = totalTasks > 0 ? Math.round((completedTasks / totalTasks) * 100) : 0;

  const plagiarismFlags = data.weeklyTests.filter(t => (t.plagiarismScore ?? 0) > 50).length;

  const touchpointOutcomes = {
    ongoing: data.touchpoints.filter(t => t.outcome === "ongoing").length,
    resolved: data.touchpoints.filter(t => t.outcome === "resolved").length,
    escalated: data.touchpoints.filter(t => t.outcome === "escalated").length,
    noActionNeeded: data.touchpoints.filter(t => t.outcome === "no_action_needed").length,
  };

  // Build the AI prompt
  const systemPrompt = `You are a senior academic mentor generating a PRIVATE comprehensive report for a student. The report combines educational, psychological, behavioral, and mentor analysis into actionable recommendations.

Output JSON ONLY — no markdown, no explanations. The JSON must match this exact shape:
{
  "accomplishments": ["Specific achievement 1", "Specific achievement 2"],
  "areasToImprove": [
    {
      "area": "Skill/behavior area",
      "current": "What's happening now (with evidence)",
      "recommendation": "Specific actionable step",
      "priority": "high"
    }
  ],
  "managementAttitude": {
    "productivitySignals": ["Signal 1", "Signal 2"],
    "professionalismSignals": ["Signal 1", "Signal 2"],
    "leadershipPotential": "One paragraph assessment",
    "managerReadiness": "Not Ready | Almost Ready | Ready | Strong",
    "focusAreas": ["Focus area 1", "Focus area 2"]
  },
  "narrative": "2-3 paragraph executive summary of the student's trajectory, strengths, and what to focus on next."
}

Rules:
1. Be specific — cite actual scores, weeks, topics. No generic advice.
2. Be honest — if the student is struggling, say so constructively.
3. Be actionable — every recommendation must be something the student can DO.
4. Be professional — never diagnose, never judge character. Focus on behavior + evidence.
5. Management attitude: assess whether the student shows signals of being able to manage others (reliability, communication, self-awareness, helping peers, taking feedback). This is forward-looking — even a beginner can show early manager signals.
6. Output in Roman (Latin) script.`;

  const dataSummary = {
    student: {
      name: data.user.name,
      currentWeek: data.user.currentWeek,
      currentDay: data.user.currentDay,
      selfPacedEnabled: data.user.selfPacedEnabled,
      enrolledAt: data.user.createdAt,
      lastLogin: data.user.lastLogin,
      project: data.user.projectName || "No project defined",
    },
    educational: {
      avgTestScore,
      weeklyTestScores: data.weeklyTests.map(t => ({ week: t.week, score: t.score, plagiarism: t.plagiarismScore ?? 0 })),
      skillMastery: data.skillMastery.map(m => ({ topic: m.topic, level: m.masteryLevel, trend: m.trend })),
      projectProgress,
      completedTasks,
      totalTasks,
      milestones: data.projectTasks.filter(t => t.isMilestone && t.status === "completed").length,
    },
    psychological: {
      wellbeingTier: data.wellbeing?.tier || "unknown",
      wellbeingReasons: (() => { try { return JSON.parse(data.wellbeing?.reasonsJson || "[]"); } catch { return []; } })(),
      dimensions: data.psychEvidence.slice(0, 21).map(e => ({ dimension: e.dimension, value: e.value, week: e.week, evidence: e.evidenceText?.slice(0, 200) })),
      calibrationGap,
      recentTestPsychAnalysis: data.weeklyTests[0]?.psychAnalysis?.slice(0, 500),
    },
    behavioral: {
      engagementScore: data.healthSummary?.engagementScore ?? 50,
      moodScore: data.healthSummary?.moodScore ?? 50,
      frustrationCount: data.healthSummary?.frustrationCount ?? 0,
      engagementStreak: data.healthSummary?.engagementStreak ?? 0,
      plagiarismFlags,
      totalInteractions: data.interactions.length,
      recentInteractionScores: data.interactions.slice(0, 10).map(i => i.correctness),
    },
    mentor: {
      touchpointCount: data.touchpoints.length,
      outcomes: touchpointOutcomes,
      recentSessions: data.touchpoints.slice(0, 5).map(t => ({ type: t.type, outcome: t.outcome, note: t.note?.slice(0, 200), date: t.createdAt })),
    },
  };

  const userPrompt = `Student data:
${JSON.stringify(dataSummary, null, 2)}

Generate the comprehensive report JSON:`;

  // Call AI
  const result = await callAI([
    { role: "system", content: systemPrompt },
    { role: "user", content: userPrompt },
  ], {
    feature: "comprehensive-report",
    temperature: 0.3,
    maxTokens: 2000,
    userId,
  });

  // Parse AI response
  let aiAnalysis: {
    accomplishments: string[];
    areasToImprove: Array<{ area: string; current: string; recommendation: string; priority: "high" | "medium" | "low" }>;
    managementAttitude: {
      productivitySignals: string[];
      professionalismSignals: string[];
      leadershipPotential: string;
      managerReadiness: string;
      focusAreas: string[];
    };
    narrative: string;
  };

  try {
    const jsonMatch = result.text?.match(/\{[\s\S]*\}/);
    aiAnalysis = JSON.parse(jsonMatch ? jsonMatch[0] : result.text || "{}");
  } catch (err) {
    logger.error("Comprehensive report: failed to parse AI JSON", {
      userId, error: err instanceof Error ? err.message : String(err),
    });
    // Fallback: generate a basic report without AI
    aiAnalysis = {
      accomplishments: [`Completed ${completedTasks}/${totalTasks} project tasks`],
      areasToImprove: [{
        area: "Test performance",
        current: `Average test score: ${avgTestScore}%`,
        recommendation: "Focus on weekly test preparation — review missed questions with the AI Tutor.",
        priority: avgTestScore < 60 ? "high" : "medium",
      }],
      managementAttitude: {
        productivitySignals: [`Engagement streak: ${data.healthSummary?.engagementStreak ?? 0} days`],
        professionalismSignals: ["Needs more data to assess"],
        leadershipPotential: "Unable to assess at this time.",
        managerReadiness: "Not Ready",
        focusAreas: ["Complete more weekly tests", "Engage consistently with the AI Tutor"],
      },
      narrative: `${data.user.name} is in Week ${data.user.currentWeek} with an average test score of ${avgTestScore}%. Project progress: ${projectProgress}%. ${data.touchpoints.length} mentor sessions recorded.`,
    };
  }

  // Build the full report object
  const report: ComprehensiveReport = {
    id: crypto.randomUUID(),
    userId,
    generatedAt: new Date().toISOString(),
    educational: {
      overallScore: avgTestScore,
      grade: scoreToGrade(avgTestScore),
      weeklyTestScores: data.weeklyTests.map(t => ({ week: t.week, score: t.score ?? 0 })),
      skillMastery: data.skillMastery.map(m => ({ topic: m.topic, level: m.masteryLevel, trend: m.trend })),
      projectProgress,
      completedTasks,
      totalTasks,
    },
    psychological: {
      wellbeingTier: data.wellbeing?.tier || "unknown",
      wellbeingReasons: (() => { try { return JSON.parse(data.wellbeing?.reasonsJson || "[]"); } catch { return []; } })(),
      dimensions: data.psychEvidence.slice(0, 21).map(e => ({
        dimension: e.dimension,
        latestValue: e.value,
        trend: "stable", // TODO: compute trend from multiple evidence entries
        evidence: e.evidenceText || "",
      })),
      calibrationGap,
      cognitiveLoad: data.psychEvidence.find(e => e.dimension === "cognitive_load")?.value || "unknown",
      mindset: data.psychEvidence.find(e => e.dimension === "attribution")?.value || "unknown",
    },
    behavioral: {
      engagementScore: data.healthSummary?.engagementScore ?? 50,
      moodScore: data.healthSummary?.moodScore ?? 50,
      attendancePattern: data.healthSummary?.engagementStreak ? `${data.healthSummary.engagementStreak} day streak` : "No streak",
      daysAheadOfSchedule: 0, // TODO: compute from self-paced status
      plagiarismFlags,
      voiceConsistency: plagiarismFlags > 0 ? "Inconsistent — review flagged tests" : "Consistent",
      disengagementSignals: data.psychEvidence.filter(e => e.value === "avoidant" || e.value === "declining_recall").map(e => e.dimension),
    },
    mentor: {
      touchpointCount: data.touchpoints.length,
      outcomes: touchpointOutcomes,
      growHistory: data.touchpoints.slice(0, 10).map(t => ({
        date: t.createdAt.toISOString(),
        type: t.type,
        outcome: t.outcome || "unknown",
        note: t.note || "",
      })),
      lastSessionDate: data.touchpoints[0]?.createdAt.toISOString() || null,
    },
    accomplishments: aiAnalysis.accomplishments || [],
    areasToImprove: aiAnalysis.areasToImprove || [],
    managementAttitude: aiAnalysis.managementAttitude || {
      productivitySignals: [],
      professionalismSignals: [],
      leadershipPotential: "Unable to assess.",
      managerReadiness: "Not Ready",
      focusAreas: [],
    },
    narrative: aiAnalysis.narrative || "",
    cached: false,
    cacheKey,
    reviewed: false, // ME-5 fix: new reports start as unreviewed
  };

  // Cache the report
  try {
    await db.aICache.upsert({
      where: { cacheKey },
      create: { cacheKey, response: JSON.stringify(report), provider: "deepseek" },
      update: { response: JSON.stringify(report), createdAt: new Date() },
    });
  } catch (err) {
    logger.warn("Failed to cache comprehensive report", { userId, error: err instanceof Error ? err.message : String(err) });
  }

  return report;
}
