"use client";

/**
 * GrowthReportPanel — student-facing view of their private growth report.
 *
 * H11 fix (audit 2026-07-26): the growth report was generated by
 * /api/growth-reports/[userId] (computed on demand) but NEVER
 * shown to anyone — students didn't know it existed, and there was no UI
 * to display it. This component surfaces:
 *   - Strengths (what went well)
 *   - Growth areas (honest shortcomings)
 *   - Academic dimension snapshot (skill mastery, test scores)
 *   - Generation date
 *
 * Wired into the student's Progress tab (ReportCardPanel).
 *
 * The report is PRIVATE — it's the honest, full picture a student shares
 * with a mentor, not an employer. The certificate stays simple + positive;
 * this is the deeper, developmental document.
 */

import { useEffect, useState, useCallback } from "react";
import { api, AI_TIMEOUT_MS } from "@/lib/api-client";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/modules/ui/card";
import { Button } from "@/modules/ui/button";
import { Badge } from "@/modules/ui/badge";
import { Loader2, RefreshCw, Sparkles, TrendingUp, TrendingDown, Lock } from "lucide-react";
import { showError, showSuccess } from "@/lib/toast-helpers";

interface GrowthReport {
  id: string;
  generatedAt: string;
  strengths: string;
  growthAreas: string;
  dimensionSnapshot: string; // JSON of academic dimensions (skill mastery, scores)
}

interface GrowthReportPanelProps {
  studentId: string;
}

export function GrowthReportPanel({ studentId }: GrowthReportPanelProps) {
  const [report, setReport] = useState<GrowthReport | null>(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async () => {
    setLoading(true);
    try {
      setError(null);
      const res = await api.get<{ report: GrowthReport }>(`/api/growth-reports/${studentId}`, undefined, AI_TIMEOUT_MS);
      setReport(res.report);
    } catch (e) {
      // 404 means no report yet — that's OK, we'll show a "generate" CTA
      if (e instanceof Error && e.message.includes("404")) {
        setReport(null);
      } else {
        setError(e instanceof Error ? e.message : "Failed to load growth report");
      }
    } finally {
      setLoading(false);
    }
  }, [studentId]);

  useEffect(() => { load(); }, [load]);

  const generate = async () => {
    setGenerating(true);
    try {
      const res = await api.get<{ report: GrowthReport }>(`/api/growth-reports/${studentId}`, undefined, AI_TIMEOUT_MS);
      setReport(res.report);
      showSuccess("Growth report generated. This is your private, honest reflection — share it with a mentor, not an employer.");
    } catch (e) {
      showError(e instanceof Error ? e.message : "Failed to generate growth report. You may need to complete more of the course first.");
    } finally {
      setGenerating(false);
    }
  };

  // Parse the dimension snapshot JSON
  let dimensions: Array<{ dimension: string; value: string }> = [];
  if (report?.dimensionSnapshot) {
    try {
      const parsed = JSON.parse(report.dimensionSnapshot);
      dimensions = Array.isArray(parsed) ? parsed : Object.entries(parsed).map(([k, v]) => ({ dimension: k, value: String(v) }));
    } catch {
      dimensions = [];
    }
  }

  if (loading) {
    return (
      <Card>
        <CardContent className="p-4 flex items-center gap-2 text-xs text-muted-foreground">
          <Loader2 className="h-3.5 w-3.5 animate-spin" /> Loading your growth report...
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className="border-violet-500/30 bg-gradient-to-br from-violet-500/5 via-background to-background">
      <CardHeader>
        <div className="flex items-center justify-between">
          <div>
            <CardTitle className="text-base flex items-center gap-2">
              <Sparkles className="h-4 w-4 text-violet-500" /> Private Growth Report
              <Badge variant="outline" className="text-[9px] border-violet-500/40 bg-violet-500/10 text-violet-700 dark:text-violet-300">
                <Lock className="h-2.5 w-2.5 mr-0.5" /> Private
              </Badge>
            </CardTitle>
            <CardDescription className="text-xs mt-0.5">
              The honest, full picture of your growth — strengths AND shortcomings. Share with a mentor, not an employer.
            </CardDescription>
          </div>
          {report && (
            <Button variant="ghost" size="sm" onClick={load} className="h-7 text-xs">
              <RefreshCw className="h-3 w-3" /> Refresh
            </Button>
          )}
        </div>
      </CardHeader>
      <CardContent className="space-y-3">
        {error && (
          <div className="rounded-md border border-destructive/30 bg-destructive/5 p-2 text-xs text-destructive">
            {error}
          </div>
        )}

        {!report && !error && (
          <div className="text-center py-6 space-y-3">
            <div className="inline-flex h-12 w-12 items-center justify-center rounded-full bg-violet-500/10">
              <Sparkles className="h-6 w-6 text-violet-500" />
            </div>
            <div>
              <p className="text-sm font-medium text-foreground">No growth report yet</p>
              <p className="text-xs text-muted-foreground mt-1 max-w-sm mx-auto">
                Your growth report is generated from your weekly test scores, skill mastery, and project work. It&apos;s an honest reflection — both what you did well and where you can grow.
              </p>
            </div>
            <Button onClick={generate} disabled={generating} className="bg-violet-500 hover:bg-violet-600 text-white">
              {generating ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Sparkles className="h-3.5 w-3.5" />}
              {generating ? "Generating..." : "Generate My Growth Report"}
            </Button>
          </div>
        )}

        {report && (
          <>
            {/* Strengths */}
            <div className="rounded-md border border-growth-sage bg-growth-sage-soft p-3">
              <p className="text-[10px] text-growth-sage-foreground uppercase tracking-wider mb-1.5 flex items-center gap-1">
                <TrendingUp className="h-3 w-3" /> Strengths
              </p>
              <p className="text-xs text-foreground leading-relaxed whitespace-pre-wrap">{report.strengths}</p>
            </div>

            {/* Growth areas */}
            <div className="rounded-md border border-growth-amber bg-growth-amber-soft p-3">
              <p className="text-[10px] text-growth-amber-foreground dark:text-growth-amber uppercase tracking-wider mb-1.5 flex items-center gap-1">
                <TrendingDown className="h-3 w-3" /> Growth Areas
              </p>
              <p className="text-xs text-foreground leading-relaxed whitespace-pre-wrap">{report.growthAreas}</p>
            </div>

            {/* Academic dimension snapshot */}
            {dimensions.length > 0 && (
              <div className="rounded-md border border-border bg-background/50 p-3">
                <p className="text-[10px] text-muted-foreground uppercase tracking-wider mb-1.5">Academic Snapshot</p>
                <div className="grid grid-cols-2 sm:grid-cols-3 gap-1.5">
                  {dimensions.map((d, i) => (
                    <div key={i} className="text-[10px]">
                      <span className="text-muted-foreground">{d.dimension}:</span>{" "}
                      <span className="text-foreground font-medium">{d.value}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}

            <p className="text-[10px] text-muted-foreground text-right">
              Generated {new Date(report.generatedAt).toLocaleDateString()}
            </p>
          </>
        )}
      </CardContent>
    </Card>
  );
}
