"use client";

import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { scoreToGrade, gradeColor, PILLARS } from "@/lib/constants";
import {
  CalendarCheck, ClipboardList, HelpCircle, TrendingUp, FileText,
  Loader2, Send, CheckCircle2, Circle, AlertTriangle, Sparkles, Brain, AlertCircle, RefreshCw,
  Sun, Moon, Monitor, Plus, Edit3, Save, Trash2, X, BookOpen, ArrowLeft, MessageSquare,
  ChevronDown, ChevronRight, Bot, ShieldAlert, Award, ExternalLink,
} from "lucide-react";
import type {
  Stats, WeeklyTest, Competency, ReportCardRow, DailyLog, Task,
  Interaction, CommentRow, StatsResponse, Mode, JourneyStep,
} from "@/components/examiner/student/types";
import { StatSquareCard, GanttChartIcon, GithubIcon, safeParse } from "@/components/examiner/student/shared";
import { FinalResultPanel } from "@/components/examiner/student/FinalResultPanel";
import { ProjectReportPanel } from "@/components/examiner/student/ProjectReportPanel";

export function ReportCardPanel({ reportCards, comments }: { reportCards: ReportCardRow[]; comments: CommentRow[] }) {
  return (
    <div className="space-y-4">
      {/* SDT rebalance: Final Result only shown when the student has completed at least
          1 weekly test. Showing "Career Readiness: Not Ready" + "0/6 tests" to a Week-1
          student is demoralizing. Replace with an encouraging empty state. */}
      <FinalResultPanel />

      {/* Project Reports — student submits weekly/final project reports + AI analyzes them */}
      <ProjectReportPanel />

      {reportCards.length === 0 ? (
        <Card className="border-border bg-card">
          <CardContent className="p-8">
            <div className="flex flex-col items-center justify-center text-center">
              <FileText className="h-10 w-10 text-muted-foreground/50 mb-3" />
              <p className="text-sm text-muted-foreground">No weekly report cards yet.</p>
              <p className="text-xs text-muted-foreground/70 mt-1 max-w-xs">
                Report cards are generated by your teacher after each weekly test. Complete your weekly test to unlock your first report card.
              </p>
            </div>
          </CardContent>
        </Card>
      ) : (
        reportCards.map((rc) => (
          <Card key={rc.week} className="border-border bg-card">
            <CardHeader>
              {/* Phase 6.2: flex-wrap so the grade + score wrap below the title on small screens */}
              <div className="flex items-center justify-between flex-wrap gap-2">
                <CardTitle className="text-foreground">Week {rc.week} Report Card</CardTitle>
                <div className="flex items-center gap-2">
                  <Badge variant="outline" className="text-xl sm:text-2xl font-bold p-2 border-border">
                    <span className={gradeColor(rc.grade)}>{rc.grade}</span>
                  </Badge>
                  <span className="text-base sm:text-lg font-semibold text-foreground/80">{rc.score}%</span>
                </div>
              </div>
            </CardHeader>
          <CardContent className="space-y-3 text-sm">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <p className="text-xs text-primary mb-1">Strengths</p>
                <ul className="text-foreground/80 list-disc list-inside">
                  {safeParse(rc.strengths).map((s, i) => <li key={i}>{s}</li>)}
                </ul>
              </div>
              <div>
                <p className="text-xs text-destructive mb-1">Weaknesses</p>
                <ul className="text-foreground/80 list-disc list-inside">
                  {safeParse(rc.weaknesses).map((s, i) => <li key={i}>{s}</li>)}
                </ul>
              </div>
            </div>
            <div><p className="text-xs text-muted-foreground">Work Habits</p><p className="text-foreground">{rc.workHabits}</p></div>
            <div><p className="text-xs text-muted-foreground">Progress</p><p className="text-foreground">{rc.progress}</p></div>
            <div><p className="text-xs text-muted-foreground">Examiner Observations</p><p className="text-foreground">{rc.examinerObservations}</p></div>
            <div>
              <p className="text-xs text-secondary-foreground mb-1">Next Steps</p>
              <ul className="text-foreground/80 list-disc list-inside">
                {safeParse(rc.nextSteps).map((s, i) => <li key={i}>{s}</li>)}
              </ul>
            </div>
            {/* Teacher comments on this report card */}
            {comments.filter(c => c.body?.includes(`[Week ${rc.week} Report Card]`)).map(c => (
              <div key={c.id} className="rounded-md bg-primary/10 border border-primary/20 p-2 text-xs">
                <div className="flex items-center justify-between mb-0.5">
                  <span className="font-medium text-primary flex items-center gap-1">
                    <MessageSquare className="h-2.5 w-2.5" /> {c.teacher.name}
                  </span>
                  <span className="text-[10px] text-muted-foreground">{new Date(c.createdAt).toLocaleDateString()}</span>
                </div>
                <p className="text-foreground/80 break-words">{c.body?.replace(`[Week ${rc.week} Report Card] `, "")}</p>
              </div>
            ))}
          </CardContent>
        </Card>
      ))
      )}
    </div>
  );
}
